language: java
services: mongodb
env: MONGODB_HOSTNAME=127.0.0.1
# jdk:
#     - openjdk7
#     - openjdk6
#     - oraclejdk7
before_install: echo "before install"
before_script: 
    - echo "before script"
    - mvn install -DskipTests=true -s ./settings-example.xml
script: 
    - echo "script"
    - mvn clean test -s ./settings-example.xml