language: java
services: mongodb
env: MONGODB_HOSTNAME=127.0.0.1
jdk:
    - openjdk7
    - openjdk6
    - oraclejdk7
before_script: mvn install -DskipTests=true -s ./settings-example.xml
script: mvn clean test -s ./settings-example.xml